/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: dbus-connection.proto */

#ifndef PROTOBUF_C_dbus_2dconnection_2eproto__INCLUDED
#define PROTOBUF_C_dbus_2dconnection_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _DBusString DBusString;
typedef struct _DBusHeaderField DBusHeaderField;
typedef struct _DBusHeader DBusHeader;
typedef struct _DBusBool DBusBool;
typedef struct _DBusCounter DBusCounter;
typedef struct _DBusDataSlot DBusDataSlot;
typedef struct _DBusDataSlotList DBusDataSlotList;
typedef struct _DBusMessage DBusMessage;
typedef struct _DBusValidity DBusValidity;
typedef struct _DBusMessageLoader DBusMessageLoader;
typedef struct _DBusAuthStateData DBusAuthStateData;
typedef struct _DBusAuthMechanismHandler DBusAuthMechanismHandler;
typedef struct _DBusCredentials DBusCredentials;
typedef struct _DBusKey DBusKey;
typedef struct _DBusKeyring DBusKeyring;
typedef struct _DBusAuth DBusAuth;
typedef struct _DBusTransport DBusTransport;
typedef struct _DBusWatch DBusWatch;
typedef struct _DBusWatchList DBusWatchList;
typedef struct _DBusTimeout DBusTimeout;
typedef struct _DBusTimeoutList DBusTimeoutList;
typedef struct _DBusHashTable DBusHashTable;
typedef struct _DBusMessageFilter DBusMessageFilter;
typedef struct _DBusDispatchStatus DBusDispatchStatus;
typedef struct _DBusObjectTree DBusObjectTree;
typedef struct _DBusConnection DBusConnection;
typedef struct _ServiceState ServiceState;


/* --- enums --- */


/* --- messages --- */

/*
 * 定义DBusString消息类型，如果没有其他说明，它可以简单地被定义为一个字符串
 */
struct  _DBusString
{
  ProtobufCMessage base;
  char *data;
};
#define DBUS_STRING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbus_string__descriptor) \
    , (char *)protobuf_c_empty_string }


/*
 * 定义DBusHeaderField消息类型
 */
struct  _DBusHeaderField
{
  ProtobufCMessage base;
  /*
   * Position of field value, or -1/-2
   */
  int32_t value_pos;
};
#define DBUS_HEADER_FIELD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbus_header_field__descriptor) \
    , 0 }


/*
 * 定义DBusHeader消息类型
 */
struct  _DBusHeader
{
  ProtobufCMessage base;
  /*
   * Header network data
   */
  DBusString *data;
  /*
   * Track the location of each field in header
   */
  size_t n_fields;
  DBusHeaderField **fields;
  /*
   * 0-7 bytes of alignment in header
   */
  uint32_t padding;
  /*
   * byte order of header
   */
  uint32_t byte_order;
};
#define DBUS_HEADER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbus_header__descriptor) \
    , NULL, 0,NULL, 0, 0 }


/*
 * 定义一个简单的布尔类型
 */
struct  _DBusBool
{
  ProtobufCMessage base;
  protobuf_c_boolean value;
};
#define DBUS_BOOL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbus_bool__descriptor) \
    , 0 }


/*
 * 定义DBusCounter消息类型
 */
struct  _DBusCounter
{
  ProtobufCMessage base;
  /*
   * current size counter value
   */
  int64_t size_value;
  /*
   * current unix fd counter value
   */
  int64_t unix_fd_value;
  /*
   * 由于proto3不支持条件编译，我们可以选择添加这些字段并在实际应用中决定是否使用
   */
  /*
   * largest ever size counter value
   */
  int64_t peak_size_value;
  /*
   * largest ever unix fd counter value
   */
  int64_t peak_unix_fd_value;
  /*
   * call notify function when crossing this size value
   */
  int64_t notify_size_guard_value;
  /*
   * call notify function when crossing this unix fd value
   */
  int64_t notify_unix_fd_guard_value;
  /*
   * notify function identifier
   */
  char *notify_function_id;
  /*
   * data for notify function (serialized or simple string)
   */
  char *notify_data;
  /*
   * TRUE if the guard value has been crossed
   */
  DBusBool *notify_pending;
};
#define DBUS_COUNTER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbus_counter__descriptor) \
    , 0, 0, 0, 0, 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, NULL }


struct  _DBusDataSlot
{
  ProtobufCMessage base;
  /*
   * 这个void*data是啥呢?
   * 暂时先不管吧
   */
  /*
   * 使用 bytes 类型来模拟 void* 类型
   */
  ProtobufCBinaryData data;
  /*
   * 提供释放函数的描述信息（不能直接存储函数指针）
   */
  char *free_data_func_info;
};
#define DBUS_DATA_SLOT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbus_data_slot__descriptor) \
    , {0,NULL}, (char *)protobuf_c_empty_string }


/*
 * DBusDataSlotList 的 protobuf 定义
 */
struct  _DBusDataSlotList
{
  ProtobufCMessage base;
  /*
   * 使用 repeated 字段表示 DBusDataSlot 的数组
   */
  size_t n_slots;
  DBusDataSlot **slots;
  int32_t n_slot;
};
#define DBUS_DATA_SLOT_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbus_data_slot_list__descriptor) \
    , 0,NULL, 0 }


struct  _DBusMessage
{
  ProtobufCMessage base;
  DBusHeader *header;
  DBusString *body;
  size_t n_counter;
  DBusCounter **counter;
  int64_t size_counter_delta;
  uint32_t changed_stamp;
  DBusDataSlotList *slot_list;
  int32_t generation;
  /*
   * 文件描述符的列表，使用int32来表示
   */
  size_t n_fds;
  int32_t *fds;
  /*
   * 数组中有效的 Unix 文件描述符数量
   */
  uint32_t n_unix_fds;
  /*
   * 数组的已分配大小
   */
  uint32_t n_unix_fds_allocated;
  /*
   * 增加的unix fd计数器的大小
   */
  int64_t unix_fd_counter_delta;
};
#define DBUS_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbus_message__descriptor) \
    , NULL, NULL, 0,NULL, 0, 0, NULL, 0, 0,NULL, 0, 0, 0 }


struct  _DBusValidity
{
  ProtobufCMessage base;
  int32_t valid_type;
};
#define DBUS_VALIDITY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbus_validity__descriptor) \
    , 0 }


struct  _DBusMessageLoader
{
  ProtobufCMessage base;
  DBusString *data;
  size_t n_messages;
  DBusMessage **messages;
  int64_t max_message_size;
  DBusValidity *corruption_reason;
  uint32_t corrupted;
  uint32_t buffer_outstanding;
  uint32_t unix_fds_outstanding;
  size_t n_unix_fds;
  int32_t *unix_fds;
  uint32_t n_unix_fds_allocated;
  uint32_t n_unix_fds;
  /*
   * 函数
   */
  char *unix_fds_change;
  /*
   * 保存void*data
   */
  ProtobufCBinaryData unix_fds_change_data;
};
#define DBUS_MESSAGE_LOADER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbus_message_loader__descriptor) \
    , NULL, 0,NULL, 0, NULL, 0, 0, 0, 0,NULL, 0, 0, (char *)protobuf_c_empty_string, {0,NULL} }


/*
 * DBusAuthStateData 的 protobuf 定义
 */
struct  _DBusAuthStateData
{
  ProtobufCMessage base;
  /*
   * 状态的名称
   */
  char *name;
  /*
   * 描述状态函数的标识符或名称
   */
  char *handler;
};
#define DBUS_AUTH_STATE_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbus_auth_state_data__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * DBusAuthMechanismHandler 的 protobuf 定义
 */
struct  _DBusAuthMechanismHandler
{
  ProtobufCMessage base;
  /*
   * 机制的名称
   */
  char *mechanism;
  /*
   * 服务端处理数据的函数标识符
   */
  char *server_data_func;
  /*
   * 服务端编码函数的标识符
   */
  char *server_encode_func;
  /*
   * 服务端解码函数的标识符
   */
  char *server_decode_func;
  /*
   * 服务端关闭函数的标识符
   */
  char *server_shutdown_func;
  /*
   * 客户端处理初始响应的函数标识符
   */
  char *client_initial_response_func;
  /*
   * 客户端处理数据的函数标识符
   */
  char *client_data_func;
  /*
   * 客户端编码函数的标识符
   */
  char *client_encode_func;
  /*
   * 客户端解码函数的标识符
   */
  char *client_decode_func;
  /*
   * 客户端关闭函数的标识符
   */
  char *client_shutdown_func;
};
#define DBUS_AUTH_MECHANISM_HANDLER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbus_auth_mechanism_handler__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * 填入具体的字段定义
 */
struct  _DBusCredentials
{
  ProtobufCMessage base;
  /*
   * 引用计数
   */
  int32_t refcount;
  /*
   * Unix 用户ID
   */
  uint64_t unix_uid;
  /*
   * Unix 组ID列表
   */
  size_t n_unix_gids;
  uint64_t *unix_gids;
  /*
   * Unix 组ID数量，可由 unix_gids 的长度推导，这里显式定义以对应原结构
   */
  int32_t n_unix_gids;
  /*
   * 进程ID
   */
  uint64_t pid;
  /*
   * Windows 安全ID
   */
  char *windows_sid;
  /*
   * Linux 安全标签
   */
  char *linux_security_label;
  /*
   * 审计数据，用 bytes 类型表示任意二进制数据
   */
  ProtobufCBinaryData adt_audit_data;
  /*
   * 审计数据的大小，可由 adt_audit_data 的长度推导，这里显式定义以对应原结构
   */
  int32_t adt_audit_data_size;
};
#define DBUS_CREDENTIALS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbus_credentials__descriptor) \
    , 0, 0, 0,NULL, 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, {0,NULL}, 0 }


struct  _DBusKey
{
  ProtobufCMessage base;
  /*
   * Identifier used to refer to the key
   */
  int32_t id;
  /*
   * When the key was generated, as a unix timestamp
   */
  int64_t creation_time;
  /*
   * The actual key
   */
  DBusString *secret;
};
#define DBUS_KEY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbus_key__descriptor) \
    , 0, 0, NULL }


struct  _DBusKeyring
{
  ProtobufCMessage base;
  /*
   * Reference count
   */
  int32_t refcount;
  /*
   * Directory containing the keyring and lockfile
   */
  DBusString *directory;
  /*
   * Keyring filename
   */
  DBusString *filename;
  /*
   * Name of lockfile
   */
  DBusString *filename_lock;
  /*
   * Keys loaded from the file
   */
  size_t n_keys;
  DBusKey **keys;
  /*
   * Number of keys, which could be derived from the length of `keys`
   */
  int32_t n_keys;
  /*
   * Credentials for the user the keyring is for
   */
  DBusCredentials *credentials;
};
#define DBUS_KEYRING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbus_keyring__descriptor) \
    , 0, NULL, NULL, NULL, 0,NULL, 0, NULL }


/*
 * DBusAuth 的 protobuf 定义
 */
struct  _DBusAuth
{
  ProtobufCMessage base;
  int32_t refcount;
  /*
   * 客户端或服务端
   */
  char *side;
  DBusString *incoming;
  DBusString *outgoing;
  /*
   * 假设这是一个已定义的复杂类型
   */
  DBusAuthStateData *state;
  /*
   * 通常用字符串替换原有的结构指针
   */
  DBusAuthMechanismHandler *mech;
  DBusString *identity;
  DBusCredentials *credentials;
  DBusCredentials *authorized_identity;
  DBusCredentials *desired_identity;
  DBusString *context;
  DBusKeyring *keyring;
  int32_t cookie_id;
  DBusString *challenge;
  /*
   * 字符串数组用于表示允许的机制
   */
  size_t n_allowed_mechs;
  char **allowed_mechs;
  /*
   * 以下是一些布尔状态标记
   */
  protobuf_c_boolean needed_memory;
  protobuf_c_boolean already_got_mechanisms;
  protobuf_c_boolean already_asked_for_initial_response;
  protobuf_c_boolean buffer_outstanding;
  protobuf_c_boolean unix_fd_possible;
  protobuf_c_boolean unix_fd_negotiated;
};
#define DBUS_AUTH__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbus_auth__descriptor) \
    , 0, (char *)protobuf_c_empty_string, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0,NULL, 0, 0, 0, 0, 0, 0 }


struct  _DBusTransport
{
  ProtobufCMessage base;
  /*
   * 从套接字读取的凭据
   */
  DBusCredentials *credentials;
  /*
   * 接收消息的最大总大小
   */
  int64_t max_live_messages_size;
  /*
   * 接收消息的最大Unix文件描述符总数
   */
  int64_t max_live_messages_unix_fds;
  DBusCounter *live_messages;
  /*
   * 连接的服务器地址
   */
  char *address;
  /*
   * 期望的服务器GUID
   */
  char *expected_guid;
  /*
   * 凭证交换和用户验证的布尔标志
   */
  /*
   * 是否已认证
   */
  protobuf_c_boolean authenticated;
  /*
   * 是否需要发送凭据
   */
  protobuf_c_boolean send_credentials_pending;
  /*
   * 是否需要接收凭据
   */
  protobuf_c_boolean receive_credentials_pending;
  /*
   * 是否为服务器端
   */
  protobuf_c_boolean is_server;
  /*
   * 是否已从认证中恢复未使用的字节
   */
  protobuf_c_boolean unused_bytes_recovered;
  /*
   * 是否允许匿名客户端连接
   */
  protobuf_c_boolean allow_anonymous;
  /*
   * 用于描述可能的回调函数和数据
   */
  /*
   * 检查Unix用户是否被授权的函数描述
   */
  char *unix_user_function;
  char *free_unix_user_data;
  /*
   * Unix用户函数的数据
   */
  ProtobufCBinaryData unix_user_data;
  /*
   * 检查Windows用户是否被授权的函数描述
   */
  char *windows_user_function;
  char *free_windows_user_data;
  /*
   * Windows用户函数的数据
   */
  ProtobufCBinaryData windows_user_data;
  DBusMessageLoader *loader;
  DBusAuth *auth;
  /*
   * 是否已断开连接
   */
  protobuf_c_boolean disconnected;
};
#define DBUS_TRANSPORT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbus_transport__descriptor) \
    , NULL, 0, 0, NULL, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, 0, 0, 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, {0,NULL}, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, {0,NULL}, NULL, NULL, 0 }


struct  _DBusWatch
{
  ProtobufCMessage base;
  /*
   * Reference count
   */
  int32_t refcount;
  /*
   * File descriptor being watched
   */
  int32_t fd;
  /*
   * Conditions to watch, such as readable, writable, etc.
   */
  uint32_t flags;
  /*
   * Callbacks and data associated with this watch
   */
  /*
   * Identifier for the watch handler function
   */
  char *handler;
  /*
   * Data passed to the handler function, serialized
   */
  ProtobufCBinaryData handler_data;
  /*
   * Identifier for function to free handler data
   */
  char *free_handler_data_function;
  /*
   * Application specific data, serialized
   */
  ProtobufCBinaryData data;
  /*
   * Identifier for function to free application data
   */
  char *free_data_function;
  /*
   * Whether the watch is enabled
   */
  protobuf_c_boolean enabled;
  /*
   * Whether there was an Out Of Memory error last time
   */
  protobuf_c_boolean oom_last_time;
};
#define DBUS_WATCH__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbus_watch__descriptor) \
    , 0, 0, 0, (char *)protobuf_c_empty_string, {0,NULL}, (char *)protobuf_c_empty_string, {0,NULL}, (char *)protobuf_c_empty_string, 0, 0 }


struct  _DBusWatchList
{
  ProtobufCMessage base;
  /*
   * Repeated field for watch objects
   */
  size_t n_watches;
  DBusWatch **watches;
  /*
   * Callbacks are represented by strings that should correspond to functions in the application
   */
  /*
   * Identifier for the callback to add a watch
   */
  char *add_watch_function;
  /*
   * Identifier for the callback to remove a watch
   */
  char *remove_watch_function;
  /*
   * Identifier for the callback on toggling watch enablement
   */
  char *watch_toggled_function;
  /*
   * Serialized data for watch callbacks, if necessary
   */
  ProtobufCBinaryData watch_data;
  /*
   * Identifier for the function to free watch data
   */
  char *watch_free_data_function;
};
#define DBUS_WATCH_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbus_watch_list__descriptor) \
    , 0,NULL, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, {0,NULL}, (char *)protobuf_c_empty_string }


struct  _DBusTimeout
{
  ProtobufCMessage base;
  /*
   * Reference count
   */
  int32_t refcount;
  /*
   * Timeout interval in milliseconds
   */
  int32_t interval;
  /*
   * Identifiers for handler functions and serialized data for handler data
   */
  /*
   * Identifier for the timeout handler function
   */
  char *handler;
  /*
   * Serialized data for the timeout handler, if needed
   */
  ProtobufCBinaryData handler_data;
  /*
   * Identifier for function to free handler data
   */
  char *free_handler_data_function;
  /*
   * Application-specific data, serialized
   */
  ProtobufCBinaryData data;
  /*
   * Identifier for function to free application data
   */
  char *free_data_function;
  /*
   * Bitfields translated to bool
   */
  /*
   * True if the timeout is active
   */
  protobuf_c_boolean enabled;
  /*
   * True if the timeout should be restarted after re-enabling
   */
  protobuf_c_boolean needs_restart;
};
#define DBUS_TIMEOUT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbus_timeout__descriptor) \
    , 0, 0, (char *)protobuf_c_empty_string, {0,NULL}, (char *)protobuf_c_empty_string, {0,NULL}, (char *)protobuf_c_empty_string, 0, 0 }


struct  _DBusTimeoutList
{
  ProtobufCMessage base;
  /*
   * List of timeout objects
   */
  size_t n_timeouts;
  DBusTimeout **timeouts;
  /*
   * Callback function identifiers for adding, removing, or toggling timeouts
   */
  /*
   * Identifier for the callback to add a timeout
   */
  char *add_timeout_function;
  /*
   * Identifier for the callback to remove a timeout
   */
  char *remove_timeout_function;
  /*
   * Identifier for the callback when a timeout is enabled/disabled or changes interval
   */
  char *timeout_toggled_function;
  /*
   * Data associated with timeout callbacks
   */
  /*
   * Serialized data for timeout callbacks
   */
  ProtobufCBinaryData timeout_data;
  /*
   * Identifier for the function to free timeout data
   */
  char *timeout_free_data_function;
};
#define DBUS_TIMEOUT_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbus_timeout_list__descriptor) \
    , 0,NULL, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, {0,NULL}, (char *)protobuf_c_empty_string }


struct  _DBusHashTable
{
  ProtobufCMessage base;
  /*
   * 这里只保存消息的序列号和对应的
   */
  uint32_t serial;
  /*
   * 这个应该是一个DBusPendingCall结构体
   */
  ProtobufCBinaryData pending_call;
};
#define DBUS_HASH_TABLE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbus_hash_table__descriptor) \
    , 0, {0,NULL} }


struct  _DBusMessageFilter
{
  ProtobufCMessage base;
  /*
   * Reference count, translated from DBusAtomic
   */
  int32_t refcount;
  /*
   * Identifier for the filter function to be invoked
   */
  char *function;
  /*
   * Serialized user data, to be passed to the filter function
   */
  ProtobufCBinaryData user_data;
  /*
   * Identifier for function to free user data
   */
  char *free_user_data_function;
};
#define DBUS_MESSAGE_FILTER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbus_message_filter__descriptor) \
    , 0, (char *)protobuf_c_empty_string, {0,NULL}, (char *)protobuf_c_empty_string }


struct  _DBusDispatchStatus
{
  ProtobufCMessage base;
  int32_t status;
};
#define DBUS_DISPATCH_STATUS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbus_dispatch_status__descriptor) \
    , 0 }


struct  _DBusObjectTree
{
  ProtobufCMessage base;
  /*
   * Reference count, translated from DBusAt
   */
  int32_t refcount;
  ProtobufCBinaryData dbusobjectsubtree;
};
#define DBUS_OBJECT_TREE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbus_object_tree__descriptor) \
    , 0, {0,NULL} }


/*
 * DBusConnection definition
 */
struct  _DBusConnection
{
  ProtobufCMessage base;
  size_t n_outgoing_messages;
  DBusMessage **outgoing_messages;
  size_t n_incoming_messages;
  DBusMessage **incoming_messages;
  size_t n_expired_messages;
  DBusMessage **expired_messages;
  DBusMessage *message_borrowed;
  /*
   * 发送队列的长度
   */
  int32_t n_outgoing;
  /*
   * 接收队列的长度
   */
  int32_t n_incoming;
  /*
   * 发送消息的大小计数器
   */
  DBusCounter *outgoing_counter;
  DBusTransport *transport;
  DBusWatchList *watches;
  DBusTimeoutList *timeouts;
  size_t n_filter_list;
  DBusMessageFilter **filter_list;
  DBusDataSlotList *slot_list;
  size_t n_pending_replies;
  DBusHashTable **pending_replies;
  uint32_t client_serial;
  size_t n_disconnect_message_link;
  DBusMessage **disconnect_message_link;
  char *server_guid;
  protobuf_c_boolean dispatch_acquired;
  protobuf_c_boolean io_path_acquired;
  protobuf_c_boolean shareable;
  protobuf_c_boolean exit_on_disconnect;
  protobuf_c_boolean builtin_filters_enabled;
  protobuf_c_boolean route_peer_messages;
  protobuf_c_boolean disconnected_message_arrived;
  protobuf_c_boolean disconnected_message_processed;
  protobuf_c_boolean have_connection_lock;
  int32_t generation;
  char *wakeup_main_function;
  ProtobufCBinaryData wakeup_main_data;
  char *free_wakeup_main_data;
  char *dispatch_status_function;
  ProtobufCBinaryData dispatch_status_data;
  char *free_dispatch_status_data;
  DBusDispatchStatus *last_dispatch_status;
  DBusObjectTree *objects;
};
#define DBUS_CONNECTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dbus_connection__descriptor) \
    , 0,NULL, 0,NULL, 0,NULL, NULL, 0, 0, NULL, NULL, NULL, NULL, 0,NULL, NULL, 0,NULL, 0, 0,NULL, (char *)protobuf_c_empty_string, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (char *)protobuf_c_empty_string, {0,NULL}, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, {0,NULL}, (char *)protobuf_c_empty_string, NULL, NULL }


/*
 * service_state
 */
struct  _ServiceState
{
  ProtobufCMessage base;
  size_t n_connection;
  DBusConnection **connection;
};
#define SERVICE_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&service_state__descriptor) \
    , 0,NULL }


/* DBusString methods */
void   dbus_string__init
                     (DBusString         *message);
size_t dbus_string__get_packed_size
                     (const DBusString   *message);
size_t dbus_string__pack
                     (const DBusString   *message,
                      uint8_t             *out);
size_t dbus_string__pack_to_buffer
                     (const DBusString   *message,
                      ProtobufCBuffer     *buffer);
DBusString *
       dbus_string__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbus_string__free_unpacked
                     (DBusString *message,
                      ProtobufCAllocator *allocator);
/* DBusHeaderField methods */
void   dbus_header_field__init
                     (DBusHeaderField         *message);
size_t dbus_header_field__get_packed_size
                     (const DBusHeaderField   *message);
size_t dbus_header_field__pack
                     (const DBusHeaderField   *message,
                      uint8_t             *out);
size_t dbus_header_field__pack_to_buffer
                     (const DBusHeaderField   *message,
                      ProtobufCBuffer     *buffer);
DBusHeaderField *
       dbus_header_field__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbus_header_field__free_unpacked
                     (DBusHeaderField *message,
                      ProtobufCAllocator *allocator);
/* DBusHeader methods */
void   dbus_header__init
                     (DBusHeader         *message);
size_t dbus_header__get_packed_size
                     (const DBusHeader   *message);
size_t dbus_header__pack
                     (const DBusHeader   *message,
                      uint8_t             *out);
size_t dbus_header__pack_to_buffer
                     (const DBusHeader   *message,
                      ProtobufCBuffer     *buffer);
DBusHeader *
       dbus_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbus_header__free_unpacked
                     (DBusHeader *message,
                      ProtobufCAllocator *allocator);
/* DBusBool methods */
void   dbus_bool__init
                     (DBusBool         *message);
size_t dbus_bool__get_packed_size
                     (const DBusBool   *message);
size_t dbus_bool__pack
                     (const DBusBool   *message,
                      uint8_t             *out);
size_t dbus_bool__pack_to_buffer
                     (const DBusBool   *message,
                      ProtobufCBuffer     *buffer);
DBusBool *
       dbus_bool__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbus_bool__free_unpacked
                     (DBusBool *message,
                      ProtobufCAllocator *allocator);
/* DBusCounter methods */
void   dbus_counter__init
                     (DBusCounter         *message);
size_t dbus_counter__get_packed_size
                     (const DBusCounter   *message);
size_t dbus_counter__pack
                     (const DBusCounter   *message,
                      uint8_t             *out);
size_t dbus_counter__pack_to_buffer
                     (const DBusCounter   *message,
                      ProtobufCBuffer     *buffer);
DBusCounter *
       dbus_counter__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbus_counter__free_unpacked
                     (DBusCounter *message,
                      ProtobufCAllocator *allocator);
/* DBusDataSlot methods */
void   dbus_data_slot__init
                     (DBusDataSlot         *message);
size_t dbus_data_slot__get_packed_size
                     (const DBusDataSlot   *message);
size_t dbus_data_slot__pack
                     (const DBusDataSlot   *message,
                      uint8_t             *out);
size_t dbus_data_slot__pack_to_buffer
                     (const DBusDataSlot   *message,
                      ProtobufCBuffer     *buffer);
DBusDataSlot *
       dbus_data_slot__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbus_data_slot__free_unpacked
                     (DBusDataSlot *message,
                      ProtobufCAllocator *allocator);
/* DBusDataSlotList methods */
void   dbus_data_slot_list__init
                     (DBusDataSlotList         *message);
size_t dbus_data_slot_list__get_packed_size
                     (const DBusDataSlotList   *message);
size_t dbus_data_slot_list__pack
                     (const DBusDataSlotList   *message,
                      uint8_t             *out);
size_t dbus_data_slot_list__pack_to_buffer
                     (const DBusDataSlotList   *message,
                      ProtobufCBuffer     *buffer);
DBusDataSlotList *
       dbus_data_slot_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbus_data_slot_list__free_unpacked
                     (DBusDataSlotList *message,
                      ProtobufCAllocator *allocator);
/* DBusMessage methods */
void   dbus_message__init
                     (DBusMessage         *message);
size_t dbus_message__get_packed_size
                     (const DBusMessage   *message);
size_t dbus_message__pack
                     (const DBusMessage   *message,
                      uint8_t             *out);
size_t dbus_message__pack_to_buffer
                     (const DBusMessage   *message,
                      ProtobufCBuffer     *buffer);
DBusMessage *
       dbus_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbus_message__free_unpacked
                     (DBusMessage *message,
                      ProtobufCAllocator *allocator);
/* DBusValidity methods */
void   dbus_validity__init
                     (DBusValidity         *message);
size_t dbus_validity__get_packed_size
                     (const DBusValidity   *message);
size_t dbus_validity__pack
                     (const DBusValidity   *message,
                      uint8_t             *out);
size_t dbus_validity__pack_to_buffer
                     (const DBusValidity   *message,
                      ProtobufCBuffer     *buffer);
DBusValidity *
       dbus_validity__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbus_validity__free_unpacked
                     (DBusValidity *message,
                      ProtobufCAllocator *allocator);
/* DBusMessageLoader methods */
void   dbus_message_loader__init
                     (DBusMessageLoader         *message);
size_t dbus_message_loader__get_packed_size
                     (const DBusMessageLoader   *message);
size_t dbus_message_loader__pack
                     (const DBusMessageLoader   *message,
                      uint8_t             *out);
size_t dbus_message_loader__pack_to_buffer
                     (const DBusMessageLoader   *message,
                      ProtobufCBuffer     *buffer);
DBusMessageLoader *
       dbus_message_loader__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbus_message_loader__free_unpacked
                     (DBusMessageLoader *message,
                      ProtobufCAllocator *allocator);
/* DBusAuthStateData methods */
void   dbus_auth_state_data__init
                     (DBusAuthStateData         *message);
size_t dbus_auth_state_data__get_packed_size
                     (const DBusAuthStateData   *message);
size_t dbus_auth_state_data__pack
                     (const DBusAuthStateData   *message,
                      uint8_t             *out);
size_t dbus_auth_state_data__pack_to_buffer
                     (const DBusAuthStateData   *message,
                      ProtobufCBuffer     *buffer);
DBusAuthStateData *
       dbus_auth_state_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbus_auth_state_data__free_unpacked
                     (DBusAuthStateData *message,
                      ProtobufCAllocator *allocator);
/* DBusAuthMechanismHandler methods */
void   dbus_auth_mechanism_handler__init
                     (DBusAuthMechanismHandler         *message);
size_t dbus_auth_mechanism_handler__get_packed_size
                     (const DBusAuthMechanismHandler   *message);
size_t dbus_auth_mechanism_handler__pack
                     (const DBusAuthMechanismHandler   *message,
                      uint8_t             *out);
size_t dbus_auth_mechanism_handler__pack_to_buffer
                     (const DBusAuthMechanismHandler   *message,
                      ProtobufCBuffer     *buffer);
DBusAuthMechanismHandler *
       dbus_auth_mechanism_handler__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbus_auth_mechanism_handler__free_unpacked
                     (DBusAuthMechanismHandler *message,
                      ProtobufCAllocator *allocator);
/* DBusCredentials methods */
void   dbus_credentials__init
                     (DBusCredentials         *message);
size_t dbus_credentials__get_packed_size
                     (const DBusCredentials   *message);
size_t dbus_credentials__pack
                     (const DBusCredentials   *message,
                      uint8_t             *out);
size_t dbus_credentials__pack_to_buffer
                     (const DBusCredentials   *message,
                      ProtobufCBuffer     *buffer);
DBusCredentials *
       dbus_credentials__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbus_credentials__free_unpacked
                     (DBusCredentials *message,
                      ProtobufCAllocator *allocator);
/* DBusKey methods */
void   dbus_key__init
                     (DBusKey         *message);
size_t dbus_key__get_packed_size
                     (const DBusKey   *message);
size_t dbus_key__pack
                     (const DBusKey   *message,
                      uint8_t             *out);
size_t dbus_key__pack_to_buffer
                     (const DBusKey   *message,
                      ProtobufCBuffer     *buffer);
DBusKey *
       dbus_key__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbus_key__free_unpacked
                     (DBusKey *message,
                      ProtobufCAllocator *allocator);
/* DBusKeyring methods */
void   dbus_keyring__init
                     (DBusKeyring         *message);
size_t dbus_keyring__get_packed_size
                     (const DBusKeyring   *message);
size_t dbus_keyring__pack
                     (const DBusKeyring   *message,
                      uint8_t             *out);
size_t dbus_keyring__pack_to_buffer
                     (const DBusKeyring   *message,
                      ProtobufCBuffer     *buffer);
DBusKeyring *
       dbus_keyring__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbus_keyring__free_unpacked
                     (DBusKeyring *message,
                      ProtobufCAllocator *allocator);
/* DBusAuth methods */
void   dbus_auth__init
                     (DBusAuth         *message);
size_t dbus_auth__get_packed_size
                     (const DBusAuth   *message);
size_t dbus_auth__pack
                     (const DBusAuth   *message,
                      uint8_t             *out);
size_t dbus_auth__pack_to_buffer
                     (const DBusAuth   *message,
                      ProtobufCBuffer     *buffer);
DBusAuth *
       dbus_auth__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbus_auth__free_unpacked
                     (DBusAuth *message,
                      ProtobufCAllocator *allocator);
/* DBusTransport methods */
void   dbus_transport__init
                     (DBusTransport         *message);
size_t dbus_transport__get_packed_size
                     (const DBusTransport   *message);
size_t dbus_transport__pack
                     (const DBusTransport   *message,
                      uint8_t             *out);
size_t dbus_transport__pack_to_buffer
                     (const DBusTransport   *message,
                      ProtobufCBuffer     *buffer);
DBusTransport *
       dbus_transport__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbus_transport__free_unpacked
                     (DBusTransport *message,
                      ProtobufCAllocator *allocator);
/* DBusWatch methods */
void   dbus_watch__init
                     (DBusWatch         *message);
size_t dbus_watch__get_packed_size
                     (const DBusWatch   *message);
size_t dbus_watch__pack
                     (const DBusWatch   *message,
                      uint8_t             *out);
size_t dbus_watch__pack_to_buffer
                     (const DBusWatch   *message,
                      ProtobufCBuffer     *buffer);
DBusWatch *
       dbus_watch__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbus_watch__free_unpacked
                     (DBusWatch *message,
                      ProtobufCAllocator *allocator);
/* DBusWatchList methods */
void   dbus_watch_list__init
                     (DBusWatchList         *message);
size_t dbus_watch_list__get_packed_size
                     (const DBusWatchList   *message);
size_t dbus_watch_list__pack
                     (const DBusWatchList   *message,
                      uint8_t             *out);
size_t dbus_watch_list__pack_to_buffer
                     (const DBusWatchList   *message,
                      ProtobufCBuffer     *buffer);
DBusWatchList *
       dbus_watch_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbus_watch_list__free_unpacked
                     (DBusWatchList *message,
                      ProtobufCAllocator *allocator);
/* DBusTimeout methods */
void   dbus_timeout__init
                     (DBusTimeout         *message);
size_t dbus_timeout__get_packed_size
                     (const DBusTimeout   *message);
size_t dbus_timeout__pack
                     (const DBusTimeout   *message,
                      uint8_t             *out);
size_t dbus_timeout__pack_to_buffer
                     (const DBusTimeout   *message,
                      ProtobufCBuffer     *buffer);
DBusTimeout *
       dbus_timeout__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbus_timeout__free_unpacked
                     (DBusTimeout *message,
                      ProtobufCAllocator *allocator);
/* DBusTimeoutList methods */
void   dbus_timeout_list__init
                     (DBusTimeoutList         *message);
size_t dbus_timeout_list__get_packed_size
                     (const DBusTimeoutList   *message);
size_t dbus_timeout_list__pack
                     (const DBusTimeoutList   *message,
                      uint8_t             *out);
size_t dbus_timeout_list__pack_to_buffer
                     (const DBusTimeoutList   *message,
                      ProtobufCBuffer     *buffer);
DBusTimeoutList *
       dbus_timeout_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbus_timeout_list__free_unpacked
                     (DBusTimeoutList *message,
                      ProtobufCAllocator *allocator);
/* DBusHashTable methods */
void   dbus_hash_table__init
                     (DBusHashTable         *message);
size_t dbus_hash_table__get_packed_size
                     (const DBusHashTable   *message);
size_t dbus_hash_table__pack
                     (const DBusHashTable   *message,
                      uint8_t             *out);
size_t dbus_hash_table__pack_to_buffer
                     (const DBusHashTable   *message,
                      ProtobufCBuffer     *buffer);
DBusHashTable *
       dbus_hash_table__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbus_hash_table__free_unpacked
                     (DBusHashTable *message,
                      ProtobufCAllocator *allocator);
/* DBusMessageFilter methods */
void   dbus_message_filter__init
                     (DBusMessageFilter         *message);
size_t dbus_message_filter__get_packed_size
                     (const DBusMessageFilter   *message);
size_t dbus_message_filter__pack
                     (const DBusMessageFilter   *message,
                      uint8_t             *out);
size_t dbus_message_filter__pack_to_buffer
                     (const DBusMessageFilter   *message,
                      ProtobufCBuffer     *buffer);
DBusMessageFilter *
       dbus_message_filter__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbus_message_filter__free_unpacked
                     (DBusMessageFilter *message,
                      ProtobufCAllocator *allocator);
/* DBusDispatchStatus methods */
void   dbus_dispatch_status__init
                     (DBusDispatchStatus         *message);
size_t dbus_dispatch_status__get_packed_size
                     (const DBusDispatchStatus   *message);
size_t dbus_dispatch_status__pack
                     (const DBusDispatchStatus   *message,
                      uint8_t             *out);
size_t dbus_dispatch_status__pack_to_buffer
                     (const DBusDispatchStatus   *message,
                      ProtobufCBuffer     *buffer);
DBusDispatchStatus *
       dbus_dispatch_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbus_dispatch_status__free_unpacked
                     (DBusDispatchStatus *message,
                      ProtobufCAllocator *allocator);
/* DBusObjectTree methods */
void   dbus_object_tree__init
                     (DBusObjectTree         *message);
size_t dbus_object_tree__get_packed_size
                     (const DBusObjectTree   *message);
size_t dbus_object_tree__pack
                     (const DBusObjectTree   *message,
                      uint8_t             *out);
size_t dbus_object_tree__pack_to_buffer
                     (const DBusObjectTree   *message,
                      ProtobufCBuffer     *buffer);
DBusObjectTree *
       dbus_object_tree__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbus_object_tree__free_unpacked
                     (DBusObjectTree *message,
                      ProtobufCAllocator *allocator);
/* DBusConnection methods */
void   dbus_connection__init
                     (DBusConnection         *message);
size_t dbus_connection__get_packed_size
                     (const DBusConnection   *message);
size_t dbus_connection__pack
                     (const DBusConnection   *message,
                      uint8_t             *out);
size_t dbus_connection__pack_to_buffer
                     (const DBusConnection   *message,
                      ProtobufCBuffer     *buffer);
DBusConnection *
       dbus_connection__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dbus_connection__free_unpacked
                     (DBusConnection *message,
                      ProtobufCAllocator *allocator);
/* ServiceState methods */
void   service_state__init
                     (ServiceState         *message);
size_t service_state__get_packed_size
                     (const ServiceState   *message);
size_t service_state__pack
                     (const ServiceState   *message,
                      uint8_t             *out);
size_t service_state__pack_to_buffer
                     (const ServiceState   *message,
                      ProtobufCBuffer     *buffer);
ServiceState *
       service_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   service_state__free_unpacked
                     (ServiceState *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*DBusString_Closure)
                 (const DBusString *message,
                  void *closure_data);
typedef void (*DBusHeaderField_Closure)
                 (const DBusHeaderField *message,
                  void *closure_data);
typedef void (*DBusHeader_Closure)
                 (const DBusHeader *message,
                  void *closure_data);
typedef void (*DBusBool_Closure)
                 (const DBusBool *message,
                  void *closure_data);
typedef void (*DBusCounter_Closure)
                 (const DBusCounter *message,
                  void *closure_data);
typedef void (*DBusDataSlot_Closure)
                 (const DBusDataSlot *message,
                  void *closure_data);
typedef void (*DBusDataSlotList_Closure)
                 (const DBusDataSlotList *message,
                  void *closure_data);
typedef void (*DBusMessage_Closure)
                 (const DBusMessage *message,
                  void *closure_data);
typedef void (*DBusValidity_Closure)
                 (const DBusValidity *message,
                  void *closure_data);
typedef void (*DBusMessageLoader_Closure)
                 (const DBusMessageLoader *message,
                  void *closure_data);
typedef void (*DBusAuthStateData_Closure)
                 (const DBusAuthStateData *message,
                  void *closure_data);
typedef void (*DBusAuthMechanismHandler_Closure)
                 (const DBusAuthMechanismHandler *message,
                  void *closure_data);
typedef void (*DBusCredentials_Closure)
                 (const DBusCredentials *message,
                  void *closure_data);
typedef void (*DBusKey_Closure)
                 (const DBusKey *message,
                  void *closure_data);
typedef void (*DBusKeyring_Closure)
                 (const DBusKeyring *message,
                  void *closure_data);
typedef void (*DBusAuth_Closure)
                 (const DBusAuth *message,
                  void *closure_data);
typedef void (*DBusTransport_Closure)
                 (const DBusTransport *message,
                  void *closure_data);
typedef void (*DBusWatch_Closure)
                 (const DBusWatch *message,
                  void *closure_data);
typedef void (*DBusWatchList_Closure)
                 (const DBusWatchList *message,
                  void *closure_data);
typedef void (*DBusTimeout_Closure)
                 (const DBusTimeout *message,
                  void *closure_data);
typedef void (*DBusTimeoutList_Closure)
                 (const DBusTimeoutList *message,
                  void *closure_data);
typedef void (*DBusHashTable_Closure)
                 (const DBusHashTable *message,
                  void *closure_data);
typedef void (*DBusMessageFilter_Closure)
                 (const DBusMessageFilter *message,
                  void *closure_data);
typedef void (*DBusDispatchStatus_Closure)
                 (const DBusDispatchStatus *message,
                  void *closure_data);
typedef void (*DBusObjectTree_Closure)
                 (const DBusObjectTree *message,
                  void *closure_data);
typedef void (*DBusConnection_Closure)
                 (const DBusConnection *message,
                  void *closure_data);
typedef void (*ServiceState_Closure)
                 (const ServiceState *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor dbus_string__descriptor;
extern const ProtobufCMessageDescriptor dbus_header_field__descriptor;
extern const ProtobufCMessageDescriptor dbus_header__descriptor;
extern const ProtobufCMessageDescriptor dbus_bool__descriptor;
extern const ProtobufCMessageDescriptor dbus_counter__descriptor;
extern const ProtobufCMessageDescriptor dbus_data_slot__descriptor;
extern const ProtobufCMessageDescriptor dbus_data_slot_list__descriptor;
extern const ProtobufCMessageDescriptor dbus_message__descriptor;
extern const ProtobufCMessageDescriptor dbus_validity__descriptor;
extern const ProtobufCMessageDescriptor dbus_message_loader__descriptor;
extern const ProtobufCMessageDescriptor dbus_auth_state_data__descriptor;
extern const ProtobufCMessageDescriptor dbus_auth_mechanism_handler__descriptor;
extern const ProtobufCMessageDescriptor dbus_credentials__descriptor;
extern const ProtobufCMessageDescriptor dbus_key__descriptor;
extern const ProtobufCMessageDescriptor dbus_keyring__descriptor;
extern const ProtobufCMessageDescriptor dbus_auth__descriptor;
extern const ProtobufCMessageDescriptor dbus_transport__descriptor;
extern const ProtobufCMessageDescriptor dbus_watch__descriptor;
extern const ProtobufCMessageDescriptor dbus_watch_list__descriptor;
extern const ProtobufCMessageDescriptor dbus_timeout__descriptor;
extern const ProtobufCMessageDescriptor dbus_timeout_list__descriptor;
extern const ProtobufCMessageDescriptor dbus_hash_table__descriptor;
extern const ProtobufCMessageDescriptor dbus_message_filter__descriptor;
extern const ProtobufCMessageDescriptor dbus_dispatch_status__descriptor;
extern const ProtobufCMessageDescriptor dbus_object_tree__descriptor;
extern const ProtobufCMessageDescriptor dbus_connection__descriptor;
extern const ProtobufCMessageDescriptor service_state__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_dbus_2dconnection_2eproto__INCLUDED */
